title: Alice Schoenauer Sebag, PhD
logo: /assets/img/Alice_Shift.PNG
description: Chief data scientist at the Inspection générale des finances and engineer of the French civil corps des ponts, des eaux et des forêts
theme: jekyll-theme-minimal
